// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGYyBSQhmQC8hcxbsY242TLqAiSruDBrM',
    appId: '1:32566390129:web:1b9165eebb31d4f14f5ad0',
    messagingSenderId: '32566390129',
    projectId: 'utspabanggi-firebase',
    authDomain: 'utspabanggi-firebase.firebaseapp.com',
    databaseURL: 'https://utspabanggi-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'utspabanggi-firebase.appspot.com',
    measurementId: 'G-FGG7509623',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbegiIjsDC9ghbGeXamS4__PO4KHpCaYA',
    appId: '1:32566390129:android:bc4825aac0ff89754f5ad0',
    messagingSenderId: '32566390129',
    projectId: 'utspabanggi-firebase',
    databaseURL: 'https://utspabanggi-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'utspabanggi-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIXe0pNAoEKXtyNbwotpWMDF7FPesJomM',
    appId: '1:32566390129:ios:3d292942d939f6c74f5ad0',
    messagingSenderId: '32566390129',
    projectId: 'utspabanggi-firebase',
    databaseURL: 'https://utspabanggi-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'utspabanggi-firebase.appspot.com',
    iosBundleId: 'com.example.utsPabAnggi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIXe0pNAoEKXtyNbwotpWMDF7FPesJomM',
    appId: '1:32566390129:ios:0b62407cab6c47624f5ad0',
    messagingSenderId: '32566390129',
    projectId: 'utspabanggi-firebase',
    databaseURL: 'https://utspabanggi-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'utspabanggi-firebase.appspot.com',
    iosBundleId: 'com.example.utsPabAnggi.RunnerTests',
  );
}
